# Generated by Django 5.0.6 on 2024-06-29 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0002_roomreservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomreservation',
            old_name='room_id',
            new_name='room',
        ),
        migrations.AlterField(
            model_name='conferenceroom',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
